name = "FooBar"
uuid = "0ea81ee1-d282-43e2-8a0b-2a6cdfe007da"
authors = ["hkauhanen <nenahuak@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
